In [6]:
import pandas as pd
import numpy as np

In [7]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [8]:
train_data.iloc[:,10:20]

LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType  \
0       Inside       Gtl      CollgCr       Norm       Norm     1Fam   
1          FR2       Gtl      Veenker      Feedr       Norm     1Fam   
2       Inside       Gtl      CollgCr       Norm       Norm     1Fam   
3       Corner       Gtl      Crawfor       Norm       Norm     1Fam   
4          FR2       Gtl      NoRidge       Norm       Norm     1Fam   
...        ...       ...          ...        ...        ...      ...   
1455    Inside       Gtl      Gilbert       Norm       Norm     1Fam   
1456    Inside       Gtl       NWAmes       Norm       Norm     1Fam   
1457    Inside       Gtl      Crawfor       Norm       Norm     1Fam   
1458    Inside       Gtl        NAmes       Norm       Norm     1Fam   
1459    Inside       Gtl      Edwards       Norm       Norm     1Fam   

     HouseStyle  OverallQual  OverallCond  YearBuilt  
0        2Story            7            5       2003  
1        1Story            6            8       1976  
2        2Story            7            5       2001  
3        2Story            7            5       1915  
4        2Story            8            5       2000  
...         ...          ...          ...        ...  
1455     2Story            6            5       1999  
1456     1Story            6            6       1978  
1457     2Story            7            9       1941  
1458     1Story            5            6       1950  
1459     1Story            5            6       1965  

[1460 rows x 10 columns]

In [9]:
train_data.iloc[:,11:20].isnull().any()

LandSlope       False
Neighborhood    False
Condition1      False
Condition2      False
BldgType        False
HouseStyle      False
OverallQual     False
OverallCond     False
YearBuilt       False
dtype: bool

In [13]:
test_data[test_data['GarageCars'].isnull()].iloc[:,60:80]

GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  \
1116          NaN         NaN         NaN        NaN        NaN          Y   

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
1116         174            0            212          0            0   

      PoolArea PoolQC  Fence MiscFeature  MiscVal  MoSold  YrSold SaleType  \
1116         0    NaN  MnPrv         NaN        0       3    2007       WD   

     SaleCondition  
1116        Alloca

In [18]:
test_data[test_data['GarageCars'] == 0].iloc[:,60:80]

GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  \
53            NaN         0.0         0.0        NaN        NaN          Y   
71            NaN         0.0         0.0        NaN        NaN          P   
79            NaN         0.0         0.0        NaN        NaN          N   
92            NaN         0.0         0.0        NaN        NaN          N   
96            NaN         0.0         0.0        NaN        NaN          N   
...           ...         ...         ...        ...        ...        ...   
1433          NaN         0.0         0.0        NaN        NaN          N   
1449          NaN         0.0         0.0        NaN        NaN          Y   
1453          NaN         0.0         0.0        NaN        NaN          Y   
1454          NaN         0.0         0.0        NaN        NaN          Y   
1457          NaN         0.0         0.0        NaN        NaN          Y   

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
53             0            0              0          0            0   
71            51            0            135          0            0   
79             0           18             18          0            0   
92           344            0              0          0          168   
96             0            0            168          0            0   
...          ...          ...            ...        ...          ...   
1433           0            0              0          0            0   
1449           0            0              0          0            0   
1453           0           34              0          0            0   
1454           0            0              0          0            0   
1457          80           32              0          0            0   

      PoolArea PoolQC  Fence MiscFeature  MiscVal  MoSold  YrSold SaleType  \
53           0    NaN    NaN         NaN        0       1    2010      Oth   
71           0    NaN  MnPrv         NaN        0       5    2010       WD   
79           0    NaN    NaN         NaN        0       6    2010       WD   
92           0    NaN    NaN         NaN        0       5    2010       WD   
96           0    NaN    NaN         NaN        0       2    2010    ConLD   
...        ...    ...    ...         ...      ...     ...     ...      ...   
1433         0    NaN    NaN         NaN        0       4    2006       WD   
1449         0    NaN    NaN         NaN        0       4    2006       WD   
1453         0    NaN  GdPrv         NaN        0       6    2006       WD   
1454         0    NaN    NaN         NaN        0       6    2006       WD   
1457         0    NaN  MnPrv        Shed      700       7    2006       WD   

     SaleCondition  
53         Abnorml  
71          Normal  
79         Abnorml  
92          Normal  
96          Normal  
...            ...  
1433        Normal  
1449        Normal  
1453        Normal  
1454        Normal  
1457        Normal  

[76 rows x 20 columns]

In [8]:
train_data['HouseStyle'] = train_data['HouseStyle'].apply(lambda x: x if x == "1Story" else "Not1Story")

In [5]:
test_data["GarageCars"].unique()

array([ 1.,  2.,  3.,  0.,  4.,  5., nan])

In [7]:
train_data["BldgType"].unique()

array(['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs'], dtype=object)

In [6]:
train_data["BsmtCond"].unique()

array(['TA', 'Gd', nan, 'Fa', 'Po'], dtype=object)

In [8]:
train_data["Heating"].unique()

array(['GasA', 'GasW', 'Grav', 'Wall', 'OthW', 'Floor'], dtype=object)

In [14]:
train_data["GarageFinish"].unique()

array(['RFn', 'Unf', 'Fin', nan], dtype=object)

In [57]:
train_data["BsmtHalfBath"].unique()

array([0, 1, 2])

In [70]:
train_data["KitchenQual"].unique()

array(['Gd', 'TA', 'Ex', 'Fa'], dtype=object)

In [21]:
train_data["Fireplaces"].unique()

array([0, 1, 2, 3])

In [12]:
np.log1p(train_data["SalePrice"]).min()

10.460270761075149